import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import Navbar from '@/components/Nabar/Navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="generator" content="RecoverMe.com" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, minimum-scale=1"
        />
        <link rel="shortcut icon" href="assets/images/logo.png" type="image/x-icon" />
        <meta name="description" content="" />
        <title>Home</title>
        <link
            rel="stylesheet"
            href="assets/web/assets/mobirise-icons2/mobirise2.css"
        />
        <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-grid.min.css" />
        <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-reboot.min.css" />
        <link rel="stylesheet" href="assets/dropdown/css/style.css" />
        <link rel="stylesheet" href="assets/socicon/css/styles.css" />
        <link rel="stylesheet" href="assets/theme/css/style.css" />
        <link
            rel="preload"
            href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i&display=swap"
            as="style"
            onload="this.onload=null;this.rel='stylesheet'"
        />
        <link
            rel="preload"
            as="style"
            href="assets/stylesheet/css/mbr-additional.css"
        />
        <link
            rel="stylesheet"
            href="assets/stylesheet/css/mbr-additional.css"
            type="text/css"
        />
      </head>
      <body className={inter.className}>
        <Navbar/>
        <div>
        {children}
        </div>
        <Footer/>
        </body>
    </html>
  )
}
